### ISSUE TITLE
Every Repo is blocked and giving 403 error. Even website is blocked.

### ISSUE THREAD

**Issue by mhmarf** [Nobara-Project/nobara-core-packages#32]
Hello and thank you a lot for you work.
I've been using Nobara since Nobara 38. In Nobara 38 there was a "no internet connection" bug that was due to google blocking Iran (or vice versa) but in Nobara 39 this was fixed, so thank you for that.

But recently (for past month) I cannot update anything. I am blocked from all:
```
$ nobara-sync cli
2024-11-19 18:42:17 - INFO - Running CLI mode...
2024-11-19 18:42:17 - INFO - Checking repositories...

2024-11-19 18:42:21 - WARNING - Errors during downloading metadata for repository 'nobara-appstream-40':
  - Status code: 403 for https://mirrors.nobaraproject.org/appstream (IP: 188.114.98.0)
  - Status code: 403 for https://mirrors.nobaraproject.org/appstream (IP: 188.114.99.0)
2024-11-19 18:42:21 - WARNING - Error: Failed to download metadata for repo 'nobara-appstream-40': Cannot prepare internal mirrorlist: Status code: 403 for https://mirrors.nobaraproject.org/appstream (IP: 188.114.99.0)
2024-11-19 18:42:26 - WARNING - Errors during downloading metadata for repository 'nobara-baseos-40':
  - Status code: 403 for https://mirrors.nobaraproject.org/baseos (IP: 188.114.98.0)
  - Status code: 403 for https://mirrors.nobaraproject.org/baseos (IP: 188.114.99.0)
2024-11-19 18:42:26 - WARNING - Error: Failed to download metadata for repo 'nobara-baseos-40': Cannot prepare internal mirrorlist: Status code: 403 for https://mirrors.nobaraproject.org/baseos (IP: 188.114.99.0)
2024-11-19 18:42:30 - WARNING - Errors during downloading metadata for repository 'nobara-baseos-multilib-40':
  - Status code: 403 for https://mirrors.nobaraproject.org/baseos-multilib (IP: 188.114.98.0)
  - Status code: 403 for https://mirrors.nobaraproject.org/baseos-multilib (IP: 188.114.99.0)
2024-11-19 18:42:30 - WARNING - Error: Failed to download metadata for repo 'nobara-baseos-multilib-40': Cannot prepare internal mirrorlist: Status code: 403 for https://mirrors.nobaraproject.org/baseos-multilib (IP: 188.114.98.0)
2024-11-19 18:42:33 - WARNING - Errors during downloading metadata for repository 'fedora':
  - Status code: 403 for https://mirrors.nobaraproject.org/fedora (IP: 188.114.98.0)
  - Status code: 403 for https://mirrors.nobaraproject.org/fedora (IP: 188.114.99.0)
2024-11-19 18:42:33 - ERROR - An unexpected error occurred: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Status code: 403 for https://mirrors.nobaraproject.org/fedora (IP: 188.114.98.0)
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/dnf/repo.py", line 574, in load
    ret = self._repo.load()
          ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/libdnf/repo.py", line 467, in load
    return _repo.Repo_load(self)
           ^^^^^^^^^^^^^^^^^^^^^
libdnf._error.Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Status code: 403 for https://mirrors.nobaraproject.org/fedora (IP: 188.114.98.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/nobara-updater", line 1348, in <module>
    main()
  File "/usr/bin/nobara-updater", line 994, in main
    check_repos()
  File "/usr/bin/nobara-updater", line 377, in check_repos
    ) = get_repolist()
        ^^^^^^^^^^^^^^
  File "/usr/bin/nobara-updater", line 261, in get_repolist
    repositories: dict[str | None, Repo] = convert_to_repo_dict(repoindex())
                                                                ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nobara_updater/dnf4.py", line 52, in repoindex
    base.fill_sack(load_system_repo=True)
  File "/usr/lib/python3.12/site-packages/dnf/base.py", line 407, in fill_sack
    self._add_repo_to_sack(r)
  File "/usr/lib/python3.12/site-packages/dnf/base.py", line 141, in _add_repo_to_sack
    repo.load()
  File "/usr/lib/python3.12/site-packages/dnf/repo.py", line 581, in load
    raise dnf.exceptions.RepoError(str(e))
dnf.exceptions.RepoError: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Status code: 403 for https://mirrors.nobaraproject.org/fedora (IP: 188.114.98.0)
```

I am also blocked from Nobara website itself:
![blocked](https://github.com/user-attachments/assets/7abe0f52-69fe-4511-a472-c06326ba1223)

**Comment by GloriousEggroll** [comment]
Hi, I'm sorry but we've updated our available mirrors. Upon doing so we realized we needed to abide by Fedora's distribution policies since we are downstream from them and U.S. Based. It is illegal for us to distribute in Iran.

Fedora is owned and managed by Americans and is therfore is restriced by US laws and as said on the Fedora Export Control Policy page, it means Fedora is restricted in "Cuba, Iran, North Korea, Syria, and the Crimea Region of Ukraine"

https://docs.fedoraproject.org/en-US/legal/export/

**Comment by mhmarf** [comment]
Hi, I understand... thank you for your response.

Still I will take this opportunity to thank you for creating Nobara Linux... about last year I bought this new PC after 8 years.. on this new PC I first tried to install Win7 but failed, then installed Linux Mint but all games were literally 1 FPS in there (due to a mesa package bug I was not aware of)!! I did not know what to do... buying a brand new PC and nothing works!! In my mind I was fearing that since my hardware was too new, Linux does not support it yet and if I want to enjoy my new PC, in the end I will have no choice but to install Microsoft's spyware... I never had upgraded after Win7 on my old PC...

But suddenly in Linux Mint forums, I saw someone with similar hardware having gaming problems and he was advised to consider Nobara Linux! I had no idea Nobara even existed... so I installed Nobara and wow! EVERYTHING was working perfectly after installation!! Nobara has been my main OS since then... so thank you very much!

(I did not say this to make you change your mind, I know you have to follow the rules... just wanted to thank you and Nobara team...)
Best wishes.
